name: Push frontend

on:
    push:
        branches:
            - feature/github-actions
        paths:
            - "apps/frontend/blog-portal/**"
            - "apps/frontend/website/**"
    workflow_run: 
        workflows: ["Setup core infrastructure"]
        types:
            - completed

jobs:
    build-and-push:
        name: Build and push frontend
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-southeast-1

            - name: Install bun
              uses: oven-sh/setup-bun@v2
              
            - name: Build static bundle
              run: |
                  bun install
                  bun run build
              working-directory: apps/frontend/blog-portal

            - name: Push to S3
              run: |
                  aws s3 sync ./dist/ s3://blog-portal-deployment-bucket/
              working-directory: apps/frontend/blog-portal